package com.example.application.service;

import org.springframework.stereotype.Service;

@Service
public class HeadServie {

    public StringBuilder gettingHead(int nbrVoie,String stationCode, String date_debut,String stationNAme,String hourDebut,String datefin,String hour_fin){

        StringBuilder exportedContent = new StringBuilder();

        if(nbrVoie == 2){

            exportedContent.append("\"" + getingnbrVoieCode(nbrVoie) +"\"")
                    .append(",\"" + stationCode +"000\"")
                    .append(",\"" + "26/06/14" +"\"")
                    .append(",\"" + stationNAme +"\"")
                    .append(",\"" + date_debut +"\"")
                    .append(",\"" + hourDebut +"\" \n");
            exportedContent.append("\"   \",\"" + datefin +"\"")
                    .append(",\"" + hour_fin +"\"")
                    .append(",\"1 \",\"01:00\"\t\t\t\t\n");
       //     exportedContent.append("\"" + nbrVoie +"\"")
            exportedContent.append("\"" + "02" +"\"")
                    .append(",\"" + 29 +"\"")
                    .append(",\"" + nbrVoie * 5 +"\"")
                    .append(",\"......\",\"......\"\t\t\t\t\n");

            exportedContent.append("\"                  \"\n");
            exportedContent.append("\"                  \"\n");
            exportedContent.append("\"0505080184A08401830283038302026D2D28030101F4041A028A020800C8\"\n");
            exportedContent.append("\"RN 17 PK 257.7 BOUARFA\",\"Generated by STERELA          \"\n");
            exportedContent.append("\"                  \",\"V100 from MAJ3/MAJ5           \"\n");
            exportedContent.append("\"                  \",\"                              \"\n");
            exportedContent.append("\"                  \",\"                              \"\n");


            return exportedContent;
        }else if(nbrVoie == 1){
            exportedContent.append("\"" + getingnbrVoieCode(nbrVoie) +"\"")
                    .append(",\"" + stationCode +"000\"")
                    .append(",\"" + "26/06/14" +"\"")
                    .append(",\"" + stationNAme +"\"")
                    .append(",\"" + date_debut +"\"")
                    .append(",\"" + hourDebut +"\" \n");
            exportedContent.append("\"   \",\"" + datefin +"\"")
                    .append(",\"" + hour_fin +"\"")
                    .append(",\"1 \",\"01:00\"\t\t\t\t\n");

            exportedContent.append("\"" + "01" +"\"")
                    .append(",\"" + 10 +"\"")
                    .append(",\"" + nbrVoie * 5 +"\"")
                    .append(",\"......\",\"......\"\t\t\t\t\n");

            exportedContent.append("\"                  \"\n");
            exportedContent.append("\"                  \"\n");
            exportedContent.append("\"FF\"\n");
            exportedContent.append("\"RR 501 PK 10.6 FES \",\"Generated by STERELA          \"\n");
            exportedContent.append("\"                  \",\"V100 from MAJ3/MAJ5           \"\n");
            exportedContent.append("\"                  \",\"                              \"\n");


            return exportedContent;
        }else if(nbrVoie == 3){
            exportedContent.append("\"" + getingnbrVoieCode(nbrVoie) +"\"")
                    .append(",\"" + stationCode +"000\"")
                    .append(",\"" + "26/06/14" +"\"")
                    .append(",\"" + stationNAme +"\"")
                    .append(",\"" + date_debut +"\"")
                    .append(",\"" + hourDebut +"\" \n");
            exportedContent.append("\"   \",\"" + datefin +"\"")
                    .append(",\"" + hour_fin +"\"")
                    .append(",\"1 \",\"01:00\"\t\t\t\t\n");

            exportedContent.append("\"" + "03" +"\"")
                    .append(",\"" + 29 +"\"")
                    .append(",\"" + nbrVoie * 5 +"\"")
                    .append(",\"......\",\"......\"\t\t\t\t\n");

            exportedContent.append("\n");
            exportedContent.append("\n");
            exportedContent.append("0505080184A08401830283038302026D2D28030101F4041A028A020800C8\n");
            exportedContent.append("RN 17 PK 257.7 BOUARFA,\"Generated by STERELA          \"\n");
            exportedContent.append("                       ,\"V100 from MAJ3/MAJ5           \"\n");
            exportedContent.append("                       ,\"                              \"\n");
            exportedContent.append("                       ,\"                              \"\n");
            exportedContent.append("                       ,\"                              \"\n");


            return exportedContent;
        }else  if(nbrVoie == 4){
            exportedContent.append("\"" + getingnbrVoieCode(nbrVoie) +"\"")
                    .append(",\"" + stationCode +"000\"")
                    .append(",\"" + "26/06/14" +"\"")
                    .append(",\"" + stationNAme +"\"")
                    .append(",\"" + date_debut +"\"")
                    .append(",\"" + hourDebut +"\" \n");
            exportedContent.append("\"   \",\"" + datefin +"\"")
                    .append(",\"" + hour_fin +"\"")
                    .append(",\"1 \",\"01:00\"\t\t\t\t\n");

            exportedContent.append("\"" + "04" +"\"")
                    .append(",\"" + 29 +"\"")
                    .append(",\"" + nbrVoie * 5 +"\"")
                    .append(",\"......\",\"......\"\t\t\t\t\n");

            exportedContent.append("\n");
            exportedContent.append("\n");
            exportedContent.append("0505080184A084018301F40FA00FA0041A028A020800C8000\n");
            exportedContent.append("A2 PK 126 MEKNES       ,\"Generated by STERELA          \"\n");

            exportedContent.append("\"                  \",\"                              \"\n");
            exportedContent.append("\"                  \",\"                              \"\n");
            exportedContent.append("\"                  \",\"                              \"\n");
            exportedContent.append("\"                  \",\"                              \"\n");
            exportedContent.append("\"                  \",\"                              \"\n");


            return exportedContent;
        }else {
            throw new RuntimeException("le nombre de voie est superieur a 4");
        }

    }


    String getingnbrVoieCode(int nbr){
        switch (nbr){
            case 1:return "v4.24";
            case 2:return  "v4.26";
            case 3:return  "v4.28";
            case 4:return  "v4.30";
        }

        return "";
    }
}
